version: "3"
services:

    webapp:
        build:
            context: .
            dockerfile: Dockerfile
        links:
            - db
        ports:
            - "5000:5000"
    db:
        image: mysql:8
        ports:
            - "32000:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "test"
            MYSQL_DATABASE: "feature_request"
        volumes:
            - ./db:/docker-entrypoint-initdb.d/:ro
